INSERT INTO ROLE (ID,NOME) VALUES (2,'USER');
INSERT INTO ROLE (ID,NOME) VALUES (1,'ADMIN');
INSERT INTO USUARIO ( ID, EMAIL, PASSWORD) VALUES ( 1, 'admin@hotmail.com', '$2a$10$whxgvtMJq.M5iwqd.dQtDeEvUrtQ6t/UMBqZ8RfGpqZP1jAQrQJk.');
INSERT INTO USUARIO_ROLES(USUARIO_ID, ROLES_ID) VALUES (1, 1);
